included:
  - BPHealth
  - BPHealthTests
disabled_rules:
  - file_length
  - function_body_length
  - type_body_length
  - line_length
  - cyclomatic_complexity
  - identifier_name
  - nesting
  - large_tuple
  - multiple_closures_with_trailing_closure
  - trailing_whitespace
opt_in_rules:
  - empty_count
  - empty_string
