const STORAGE = { records: 'maixiang.records.v1', profile: 'maixiang.profile.v1' };
const $ = (selector) => document.querySelector(selector);
const $$ = (selector) => [...document.querySelectorAll(selector)];
const state = { records: JSON.parse(localStorage.getItem(STORAGE.records) || '[]'), profile: JSON.parse(localStorage.getItem(STORAGE.profile) || 'null'), timeMode: 'now', filter: 'all' };

function formatDate(date, withYear = false) { const d = new Date(date); if (Number.isNaN(d.getTime())) return '时间未知'; return d.toLocaleString('zh-CN', { month: 'long', day: 'numeric', weekday: 'short', ...(withYear ? { year: 'numeric' } : {}), hour: '2-digit', minute: '2-digit', hour12: false }); }
function shortDay(date) { return new Date(date).toLocaleDateString('zh-CN', { weekday: 'short' }).replace('周',''); }
function save() { localStorage.setItem(STORAGE.records, JSON.stringify(state.records)); if (state.profile) localStorage.setItem(STORAGE.profile, JSON.stringify(state.profile)); }
function classify(sys, dia) { if (sys < 90 || dia < 60) return { key:'低血压', label:'偏低', tone:'low', caption:'建议补充水分，留意头晕乏力' }; if (sys >= 140 || dia >= 90) return { key:'高血压', label:'偏高', tone:'high', caption:'今天少盐一点，给心脏留空间' }; if (sys >= 130 || dia >= 80) return { key:'偏高', label:'临界偏高', tone:'high', caption:'接近偏高区间，连续观察几天' }; return { key:'正常', label:'正常', tone:'normal', caption:'状态平稳，继续保持这个节奏' }; }
function dietFor(status) { const advice = { '高血压': ['今天少一点盐', '优先选择清蒸、炖煮的食物，用柠檬、香草替代额外盐分。'], '偏高': ['给餐盘加一抹绿色', '多吃一份深色蔬菜，饮料换成水，晚餐尽量在睡前 3 小时完成。'], '低血压': ['慢一点，也吃够', '分多次补水，搭配鸡蛋、豆类等蛋白质；起身时给自己几秒缓冲。'], '正常': ['把好状态吃出来', '保持蔬菜、全谷物和优质蛋白的组合，今天也别忘了规律喝水。'] }; return advice[status] || ['建立你的第一笔记录', '记录血压后，这里会根据状态给你一条简单、可执行的饮食建议。']; }
function renderProfile() { const profile = state.profile || {}; $('#nameInput').value = profile.name || ''; $('#ageInput').value = profile.age || ''; if (profile.sex) { const radio = document.querySelector(`input[name="sex"][value="${profile.sex}"]`); if (radio) radio.checked = true; } $('#profileInitial').textContent = (profile.name || '我').slice(0,1); }
function renderDashboard() { const latest = state.records[0]; const now = new Date(); $('#todayLabel').textContent = `${now.getMonth()+1} 月 ${now.getDate()} 日`; $('#nowTimeLabel').textContent = now.toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'}); $('#streakText').textContent = `连续 ${getStreak()} 天`; if (!latest) { $('#latestTime').textContent='还没有记录'; $('#latestSystolic').textContent='—'; $('#latestDiastolic').textContent='—'; $('#statusPill').textContent='等待记录'; $('#statusPill').className='status-pill empty'; $('#statusCaption').textContent='记录一笔，看看今天的状态'; $('#adviceTitle').textContent='建立你的第一笔记录'; $('#adviceText').textContent=dietFor().at(1); } else { const c=classify(latest.systolic,latest.diastolic); $('#latestTime').textContent=formatDate(latest.measuredAt); $('#latestSystolic').textContent=latest.systolic; $('#latestDiastolic').textContent=latest.diastolic; $('#statusPill').textContent=c.label; $('#statusPill').className=`status-pill ${c.tone}`; $('#statusCaption').textContent=c.caption; const advice=dietFor(c.key); $('#adviceTitle').textContent=advice[0]; $('#adviceText').textContent=advice[1]; } renderChart(); }
function getStreak() { const days = new Set(state.records.map(r => new Date(r.measuredAt).toLocaleDateString('zh-CN'))); let count=0; const d=new Date(); while(days.has(d.toLocaleDateString('zh-CN'))) { count++; d.setDate(d.getDate()-1); } return count; }
function renderChart() { const root=$('#weekChart'); const days=[]; for(let i=6;i>=0;i--){const d=new Date();d.setHours(0,0,0,0);d.setDate(d.getDate()-i); const dayRecords=state.records.filter(r=>{const rd=new Date(r.measuredAt);return rd.toDateString()===d.toDateString()}); days.push({d, record:dayRecords[0]});} root.innerHTML=days.map(({d,record})=>{const c=record?classify(record.systolic,record.diastolic):null; const sH=record?Math.min(82,Math.max(8,(record.systolic-60)*.55)):4; const dH=record?Math.min(70,Math.max(6,(record.diastolic-35)*.65)):4; return `<div class="day-column ${d.toDateString()===new Date().toDateString()?'today':''}"><div class="bar-stack"><i class="bar ${c?.tone||''}" style="height:${sH}px"></i><i class="bar ${c?.tone||''}" style="height:${dH}px;opacity:.55"></i></div><span class="day-label">${shortDay(d)}</span></div>`}).join(''); }
function renderRecords() { const filtered=state.records.filter(r=>state.filter==='all'||classify(r.systolic,r.diastolic).key===state.filter); const root=$('#recordsList'); if(!filtered.length){root.innerHTML='<div class="empty-state"><strong>还没有符合条件的记录</strong><span>点击“记录一次血压”，从今天开始。</span></div>';return;} root.innerHTML=filtered.map(r=>{const c=classify(r.systolic,r.diastolic);return `<article class="record-item"><div><div class="record-date">${formatDate(r.measuredAt,true)}</div><div class="record-values">${r.systolic}<small> / </small>${r.diastolic}<small> mmHg</small></div><div class="record-meta"><span class="mini-tag">${r.fasting==='是'?'空腹':'餐后'}</span>${r.note?`<span class="mini-tag">${escapeHtml(r.note)}</span>`:''}</div></div><div class="record-status ${c.tone}">${c.label}<br><span style="font-weight:400;color:var(--muted)">${r.pulse?`心率 ${r.pulse}`:''}</span></div></article>`}).join(''); }
function escapeHtml(text) { return String(text).replace(/[&<>'"]/g, c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c])); }
function openModal(){ $('#recordModal').classList.add('open'); $('#recordModal').setAttribute('aria-hidden','false'); setTimeout(()=>$('#systolicInput').focus(),100); }
function closeModal(){ $('#recordModal').classList.remove('open'); $('#recordModal').setAttribute('aria-hidden','true'); $('#recordForm').reset(); $('#formError').textContent=''; state.timeMode='now'; $$('.time-toggle').forEach(b=>b.classList.toggle('active',b.dataset.timeMode==='now')); $('#manualTimeInput').classList.remove('show'); }
function showToast(text){const t=$('#toast');t.textContent=text;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200);}
function switchView(id){ $$('.view').forEach(v=>v.classList.toggle('active',v.id===id)); $$('.tab').forEach(t=>t.classList.toggle('active',t.dataset.view===id)); if(id==='recordsView')renderRecords(); if(id==='profileView')renderProfile(); window.scrollTo({top:0,behavior:'smooth'}); }

$('#openRecordButton').addEventListener('click',openModal); $('#closeModal').addEventListener('click',closeModal); $('#recordModal').addEventListener('click',e=>{if(e.target.id==='recordModal')closeModal();}); $('#profileButton').addEventListener('click',()=>switchView('profileView')); $('#viewAllButton').addEventListener('click',()=>switchView('recordsView')); $$('.tab').forEach(t=>t.addEventListener('click',()=>switchView(t.dataset.view))); $$('.filter-chip').forEach(chip=>chip.addEventListener('click',()=>{$$('.filter-chip').forEach(c=>c.classList.remove('active'));chip.classList.add('active');state.filter=chip.dataset.filter;renderRecords();}));
$$('.time-toggle').forEach(button=>button.addEventListener('click',()=>{state.timeMode=button.dataset.timeMode;$$('.time-toggle').forEach(b=>b.classList.toggle('active',b===button));$('#manualTimeInput').classList.toggle('show',state.timeMode==='manual');if(state.timeMode==='manual'&&!$('#manualTimeInput').value){const d=new Date();d.setMinutes(d.getMinutes()-d.getTimezoneOffset());$('#manualTimeInput').value=d.toISOString().slice(0,16);}}));
$('#recordForm').addEventListener('submit',e=>{e.preventDefault();const systolic=Number($('#systolicInput').value),diastolic=Number($('#diastolicInput').value);if(!systolic||!diastolic||systolic<=diastolic){$('#formError').textContent='请确认高压高于低压，并填写有效数值。';return;}const measuredAt=state.timeMode==='manual'?new Date($('#manualTimeInput').value).toISOString():new Date().toISOString();state.records.unshift({id:crypto.randomUUID(),systolic,diastolic,fasting:document.querySelector('input[name="fasting"]:checked').value,note:$('#noteInput').value.trim(),measuredAt});save();closeModal();renderDashboard();showToast('已保存，今天的状态更新了');});
$('#profileForm').addEventListener('submit',e=>{e.preventDefault();const age=Number($('#ageInput').value);if(!age||age<1||age>120){showToast('请输入 1–120 岁的年龄');return;}state.profile={name:$('#nameInput').value.trim(),age,sex:document.querySelector('input[name="sex"]:checked').value};save();renderProfile();showToast('个人资料已保存');switchView('dashboardView');});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&$('#recordModal').classList.contains('open'))closeModal();}); renderProfile(); renderDashboard();
